# Form implementation generated from reading ui file 'animeAppUI.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    # Function for all the windows, pages, and layout of the application.
    def setupUi(self, MainWindow):
        # MainWindow SPECIFICATIONS
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 475)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)

        # Create the central widget for the MainWindow.
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget") # Object names are useful for defining specific features in Qt StyleSheets (similar to CSS).
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        # StackedWidget (for defining multiple pages for the application) SPECIFICATIONS.

        # Defining the StackedWidget
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")

        # Create a widget for the login page
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        # Define the login page layout.
        self.gridLayout_3 = QtWidgets.QGridLayout(self.login_page)
        self.gridLayout_3.setHorizontalSpacing(4)
        self.gridLayout_3.setVerticalSpacing(15)
        self.gridLayout_3.setObjectName("gridLayout_3")
        # Create vertical and horizontal spacing around the borders of the login page.
        spacerItem = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 3, 0, 1, 2) # (row, col, rowspan, colspan) - left space
        spacerItem1 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 3, 6, 1, 2) # right space
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 4, 2, 1, 1) # bottom space
        spacerItem3 = QtWidgets.QSpacerItem(20, 39, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 0, 2, 1, 1) # top space
        # Create a label
        self.label = QtWidgets.QLabel(parent=self.login_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 2, 1, 4)
        # Create a button
        self.login_button = QtWidgets.QPushButton(parent=self.login_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_button.sizePolicy().hasHeightForWidth())
        self.login_button.setSizePolicy(sizePolicy)
        self.login_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.login_button.setObjectName("login_button")
        self.gridLayout_3.addWidget(self.login_button, 3, 2, 1, 4)
        # Create a line edit to allow the user to enter their username.
        self.user_entry = QtWidgets.QLineEdit(parent=self.login_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_entry.sizePolicy().hasHeightForWidth())
        self.user_entry.setSizePolicy(sizePolicy)
        self.user_entry.setMaximumSize(QtCore.QSize(16777215, 40))
        self.user_entry.setObjectName("user_entry")
        self.gridLayout_3.addWidget(self.user_entry, 2, 5, 1, 1)
        # Create a label
        self.label_2 = QtWidgets.QLabel(parent=self.login_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 2, 1, 3)
        # Add the login page to the StackedWidget
        self.stackedWidget.addWidget(self.login_page)

        # Create a widget for the search page.
        self.search_page = QtWidgets.QWidget()
        self.search_page.setObjectName("search_page")
        # Define the search page layout.
        self.gridLayout_4 = QtWidgets.QGridLayout(self.search_page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        # Define the search page as a ScrollArea
        self.scrollArea = QtWidgets.QScrollArea(parent=self.search_page)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn) # Enable the V scrollbar
         #self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff) # Disable the H scrollbar
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        # Create a widget to hold the contents of the ScrollArea
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 394, 206))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents) # OR self.gridLayout_5 = QtWidgets.QGridLayout()
                                                                                    # self.scrollAreaWidgetContents.setLayout(self.gridLayout_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        # Create a button.
        "self.profile_button = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)"
        self.profile_button = QtWidgets.QPushButton()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profile_button.sizePolicy().hasHeightForWidth())
        self.profile_button.setSizePolicy(sizePolicy)
        self.profile_button.setObjectName("profile_button")
        "self.gridLayout_5.addWidget(self.profile_button, 2, 0, 1, 1)"
        # Create a button
        "self.filter_button = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)"
        self.filter_button = QtWidgets.QPushButton()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter_button.sizePolicy().hasHeightForWidth())
        self.filter_button.setSizePolicy(sizePolicy)
        self.filter_button.setObjectName("filter_button")
        "self.gridLayout_5.addWidget(self.filter_button, 3, 0, 1, 1)"
        # Connect the scroll contents widget to the ScrollArea, then add the ScrollArea to a grid on the search page.
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)
        # Add the search page to the StackedWidget
        self.stackedWidget.addWidget(self.search_page)

        # Create a widget for the anime page.
        self.anime_page = QtWidgets.QWidget()
        self.anime_page.setObjectName("anime_page")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.anime_page)
        self.gridLayout_6.setObjectName("gridLayout_6")
        # Define the anime page as a ScrollArea.
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=self.anime_page)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn) # Enable the V scrollbar
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff) # Disable the H scrollbar
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        # Create a widget to hold the contents of the ScrollArea.
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 394, 206))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        # Create a button
        self.profile_button_2 = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profile_button_2.sizePolicy().hasHeightForWidth())
        self.profile_button_2.setSizePolicy(sizePolicy)
        self.profile_button_2.setObjectName("profile_button_2")
        self.gridLayout_7.addWidget(self.profile_button_2, 0, 0, 1, 1)
        # Create a button
        self.search_button = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_button.sizePolicy().hasHeightForWidth())
        self.search_button.setSizePolicy(sizePolicy)
        self.search_button.setObjectName("search_button")
        self.gridLayout_7.addWidget(self.search_button, 0, 1, 1, 1)
        # Connect the scroll contents widget to the ScrollArea, then add the ScrollArea to a grid on the anime page.
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_6.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        # Add the anime page to the StackedWidget
        self.stackedWidget.addWidget(self.anime_page)

        # Create a widget for the profile page.
        self.profile_page = QtWidgets.QWidget()
        self.profile_page.setObjectName("profile_page")
        self.gridLayout_profile = QtWidgets.QGridLayout(self.profile_page)
        self.gridLayout_profile.setObjectName("gridLayout_profile")
        # Create a button
        "self.search_button_2 = QtWidgets.QPushButton(parent=self.profile_page)"
        self.search_button_2 = QtWidgets.QPushButton()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_button_2.sizePolicy().hasHeightForWidth())
        self.search_button_2.setSizePolicy(sizePolicy)
        self.search_button_2.setObjectName("search_button_2")
        "self.gridLayout_profile.addWidget(self.search_button_2, 0, 0, 1, 1)"
        # Create a button
        "self.list_button = QtWidgets.QPushButton(parent=self.profile_page)"
        self.list_button = QtWidgets.QPushButton()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_button.sizePolicy().hasHeightForWidth())
        self.list_button.setSizePolicy(sizePolicy)
        self.list_button.setObjectName("list_button")
        "self.gridLayout_profile.addWidget(self.list_button, 0, 1, 1, 1)"
        # Add the profile page to the StackedWidget
        self.stackedWidget.addWidget(self.profile_page)

        # Create a widget for the list page.
        self.list_page = QtWidgets.QWidget()
        self.list_page.setObjectName("list_page")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.list_page)
        self.gridLayout_9.setObjectName("gridLayout_9")
        # Define the list page as a ScrollArea.
        self.scrollArea_3 = QtWidgets.QScrollArea(parent=self.list_page)
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        # Define a widget to hold the contents of the ScrollArea
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 394, 206))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        # Create a button
        self.profile_button_3 = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profile_button_3.sizePolicy().hasHeightForWidth())
        self.profile_button_3.setSizePolicy(sizePolicy)
        self.profile_button_3.setObjectName("profile_button_3")
        self.gridLayout_10.addWidget(self.profile_button_3, 0, 0, 1, 1)
        # Create a button
        self.search_button_3 = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_button_3.sizePolicy().hasHeightForWidth())
        self.search_button_3.setSizePolicy(sizePolicy)
        self.search_button_3.setObjectName("search_button_3")
        self.gridLayout_10.addWidget(self.search_button_3, 0, 1, 1, 1)
        # Connect the scroll contents widget to the ScrollArea, then add the ScrollArea to a grid on the list page.
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_9.addWidget(self.scrollArea_3, 0, 0, 1, 1)
        # Add the list page to the StackedWidget
        self.stackedWidget.addWidget(self.list_page)
        
        # Add the StackedWidget itself to the grid on the MainWindow
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        # Set the CentralWidget of the MainWindow
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 433, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # Function for setting the text of buttons and placeholders
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Anime Watchlist Management System (AWMS)"))
        self.label.setText(_translate("MainWindow", "Login"))
        self.login_button.setText(_translate("MainWindow", "Submit"))
        self.user_entry.setPlaceholderText(_translate("MainWindow", "Enter your username"))
        self.label_2.setText(_translate("MainWindow", "Username:"))
        self.profile_button.setText(_translate("MainWindow", "Profile"))
        self.filter_button.setText(_translate("MainWindow", "Search"))
        self.profile_button_2.setText(_translate("MainWindow", "Profile"))
        self.search_button.setText(_translate("MainWindow", "Search page"))
        self.search_button_2.setText(_translate("MainWindow", "Search Page"))
        self.list_button.setText(_translate("MainWindow", "Anime List"))
        self.profile_button_3.setText(_translate("MainWindow", "Profile"))
        self.search_button_3.setText(_translate("MainWindow", "Search page"))
